#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
# fix issue with https://github.com/home-assistant/core/issues/95192
pip install git+https://github.com/boto/botocore
